services:
  payment-service:
    build: .
    ports:
      - "50051:50051"
    env_file: 
      - .env
    depends_on:
      - db
      - rabbitmq

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: payments
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
