services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5673:5673" # RabbitMQ broker port
      - "15673:15673" # RabbitMQ Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest # Default username
      RABBITMQ_DEFAULT_PASS: guest # Default password
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge